# Generated by Django 3.2 on 2023-03-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('prospect', models.CharField(max_length=200)),
                ('communication', models.TextField()),
                ('response', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
