# Generated by Django 3.2 on 2023-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='communication',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='data',
            name='response',
            field=models.CharField(max_length=200),
        ),
    ]
