# Generated by Django 3.2 on 2023-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230324_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sno',
            field=models.IntegerField(unique=True),
        ),
    ]
